spring.application.name=roomzy

# Database Config (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/PgMaintenance
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liLnQ2LMEFgJXyca
spring.security.oauth2.client.registration.github.client-secret=d511c367f2a876e07912b6e0e40861b4318eee7d
spring.security.oauth2.client.registration.github.scope=read:user, user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login
